#!/usr/bin/with-contenv bash

set -e

addgroup postfix opendkim

mkdir -p /var/spool/postfix/pid \
  && chown -R 0:0 /var/spool/postfix/pid

TEMPLATES_DIR=/etc/templates
dockerize \
  -template $TEMPLATES_DIR/postfix/aliases.tmpl:/etc/postfix/aliases \
  -template $TEMPLATES_DIR/postfix/canonical.tmpl:/etc/postfix/canonical \
  -template $TEMPLATES_DIR/postfix/generic.tmpl:/etc/postfix/generic \
  -template $TEMPLATES_DIR/postfix/main.cf.tmpl:/etc/postfix/main.cf \
  -template $TEMPLATES_DIR/postfix/master.cf.tmpl:/etc/postfix/master.cf \
  -template $TEMPLATES_DIR/opendkim/opendkim.conf.tmpl:/etc/opendkim/opendkim.conf \
  -template $TEMPLATES_DIR/opendkim/key.table.tmpl:/etc/opendkim/key.table \
  -template $TEMPLATES_DIR/opendkim/signing.table.tmpl:/etc/opendkim/signing.table \
  -template $TEMPLATES_DIR/opendkim/trusted.hosts.tmpl:/etc/opendkim/trusted.hosts \
  -template $TEMPLATES_DIR/syslog/syslog.conf.tmpl:/etc/syslog.conf \
  -template $TEMPLATES_DIR/scripts/test-mail.sh.tmpl:/usr/local/bin/test-mail.sh

echo "Creating temporary self-signed certificate for $JMAIL_ORIGIN"
echo "Copy everything between the dashed lines into your mail client to trust the certificate"
openssl req -x509 -noenc -sha384 -days 3650 -utf8 \
  -newkey ec:<(openssl ecparam -name secp384r1) \
  -keyout $TEMPLATES_DIR/postfix/ssl/server.key \
  -out $TEMPLATES_DIR/postfix/ssl/server.crt \
  -subj "/O=Jmail Self-Signed Server Cert/CN=$JMAIL_ORIGIN" \
  -addext "basicConstraints=critical,CA:FALSE" \
  -addext="extendedKeyUsage=critical,serverAuth" \
  -addext "keyUsage=critical,nonRepudiation,digitalSignature,keyEncipherment,keyAgreement" \
  -addext "subjectAltName=DNS:$JMAIL_ORIGIN"

cat $TEMPLATES_DIR/postfix/ssl/server.crt
echo "-----"

POSTFIX_SSL_DIR=/etc/postfix/ssl
if [[ ! -d "${POSTFIX_SSL_DIR}" ]]; then
  mkdir -p $POSTFIX_SSL_DIR
  cp -R /etc/templates/postfix/ssl/* $POSTFIX_SSL_DIR
fi

POSTFIX_SSL_GENERATE_FILE="${POSTFIX_SSL_DIR}/.generate"
echo "Checking SSL regeneration trigger"
if [[ -f "${POSTFIX_SSL_GENERATE_FILE}" ]]; then
  cp -R /etc/templates/postfix/ssl/* $POSTFIX_SSL_DIR
  rm -f "${POSTFIX_SSL_GENERATE_FILE}"
fi

postmap /etc/postfix/canonical
postmap /etc/postfix/generic
newaliases

# TODO: Add support for Ed25519 dkim keys
OPENDKIM_KEYS_DIR=/etc/opendkim/keys/$JMAIL_ORIGIN
if [[ ! -d "${OPENDKIM_KEYS_DIR}" ]]; then
  echo "Creating DKIM keys for $JMAIL_ORIGIN"
  mkdir -p $OPENDKIM_KEYS_DIR
  opendkim-genkey -b 1024 -d $JMAIL_ORIGIN -D $OPENDKIM_KEYS_DIR -s sendonly
  chown -R 0:0 $OPENDKIM_KEYS_DIR/sendonly.private
fi

OPENDKIM_KEYS_GENERATE_FILE=/etc/opendkim/keys/$JMAIL_ORIGIN/.generate
echo "Checking DKIM regeneration trigger for $JMAIL_ORIGIN"
if [[ -f "${OPENDKIM_GENERATE_FILE}" ]]; then
  echo "Re-generate DKIM keys for $JMAIL_ORIGIN"
  opendkim-genkey -b 1024 -d $JMAIL_ORIGIN -D $OPENDKIM_KEYS_DIR -s sendonly
  chown -R 0:0 $OPENDKIM_KEYS_DIR/sendonly.private
  rm -f "${OPENDKIM_KEYS_GENERATE_FILE}"
fi

cat $OPENDKIM_KEYS_DIR/sendonly.txt
